Attribute VB_Name = "mDBCreate"
' DBCreate.bas
' Source Code Generated by Database Code Builder.
' Author:  Global Constructs

Option Explicit

' This is the database object which is referenced
' for creating this database.
Public LibraryDB As Database

' FieldDesign contains the features, properties,
' and attributes which affect the field's creation.
Private Type FieldDesign
    fdName As String
    fdType As Integer
    fdSize As Integer
    fdAllowZeroLength As Boolean
    fdAttributes As Long
    fdDefaultValue As String
    fdOrdinalPosition As Integer
    fdRequired As Boolean
    fdValidationRule As String
    fdValidationText As String
End Type

' IndexDesign contains the features, properties,
' and attributes which affect the index's creation.
Private Type IndexDesign
    idInitialized As Boolean
    idClustered As Boolean
    idIgnoreNulls As Boolean
    idName As String
    idPrimary As Boolean
    idRequired As Boolean
    idUnique As Boolean
    idFieldName() As String
End Type

' RelationDesign contains the features, properties,
' and attributes which affect the relation's creation.
Private Type RelationDesign
    rdInitialized As Boolean
    rdAttributes As Long
    rdName As String
    rdTable As String
    rdForeignTable As String
    rdFieldName() As String
    rdForeignName() As String
End Type

'
' DisplayError() displays the function name,
' error number, and text description encountered.
'
Private Sub DisplayError(sError As String)
    MsgBox sError & Chr(13) & Err.Number & " : " & Err.Description, vbCritical
    Err.Clear
End Sub

'
' CreateField() creates field with the desired features.
'
Private Sub CreateField(oTableName As TableDef, zFieldInfo As FieldDesign)
    Dim myField As Field

    On Error Resume Next
    Set myField = oTableName.CreateField(zFieldInfo.fdName, zFieldInfo.fdType)
    If Err <> 0 Then
        DisplayError "CreateField():" & oTableName.Name
        GoTo errorhandler
    End If
    If zFieldInfo.fdType = dbText Then myField.Size = zFieldInfo.fdSize

    If zFieldInfo.fdType = dbText Or zFieldInfo.fdType = dbMemo Then
        myField.AllowZeroLength = zFieldInfo.fdAllowZeroLength
    End If
    With myField
        .Attributes = zFieldInfo.fdAttributes
        .DefaultValue = zFieldInfo.fdDefaultValue
        .OrdinalPosition = zFieldInfo.fdOrdinalPosition
        .Required = zFieldInfo.fdRequired
        .ValidationRule = zFieldInfo.fdValidationRule
        .ValidationText = zFieldInfo.fdValidationText
    End With

    oTableName.Fields.Append myField
    If Err <> 0 Then DisplayError "CreateField().Append: " & oTableName.Name
errorhandler:
    InitField zFieldInfo
End Sub

'
' AddIndex() creates an index for the
' specified table.
'
Private Sub AddIndex(oTableName As TableDef, zIndexInfo As IndexDesign)
    Dim myIndex As Index
    Dim myField As Field
    Dim i As Integer

    On Error Resume Next
    Set myIndex = oTableName.CreateIndex(zIndexInfo.idName)
    If Err <> 0 Then
        DisplayError "AddIndex(): " & zIndexInfo.idName
        GoTo errorhandler
    End If
    ' Add field names to index
    For i = LBound(zIndexInfo.idFieldName) To UBound(zIndexInfo.idFieldName)
        Set myField = myIndex.CreateField(zIndexInfo.idFieldName(i))
        If Err <> 0 Then
            DisplayError "AddIndex(): " & zIndexInfo.idName & "-" & zIndexInfo.idFieldName(i)
            GoTo errorhandler
        End If
        With myIndex
            .Clustered = zIndexInfo.idClustered
            .IgnoreNulls = zIndexInfo.idIgnoreNulls
            .Primary = zIndexInfo.idPrimary
            .Required = zIndexInfo.idRequired
            .Unique = zIndexInfo.idUnique
            .Fields.Append myField
        End With
        If Err <> 0 Then
            DisplayError "AddIndex().Append: Field-" & zIndexInfo.idFieldName(i)
            GoTo errorhandler
        End If
    Next i
    ' Append index to table
    oTableName.Indexes.Append myIndex
    If Err <> 0 Then DisplayError "AddIndex().Append"
errorhandler:
    InitIndex zIndexInfo
End Sub

'
' AddRelation() creates a relationship for the
' specified database.
'
Private Sub AddRelation(oDatabase As Database, zRelationInfo As RelationDesign)
    Dim myRelation As Relation
    Dim myField As Field
    Dim i As Integer

    ' Add the Relationship
    On Error Resume Next
    Set myRelation = oDatabase.CreateRelation(zRelationInfo.rdName)
    If Err <> 0 Then
        DisplayError "AddRelation(): " & zRelationInfo.rdName
        GoTo errorhandler
    End If
    With myRelation
        .Table = zRelationInfo.rdTable  'Name the Primary Table.
        .ForeignTable = zRelationInfo.rdForeignTable 'Name the Foreign Table.
        .Attributes = zRelationInfo.rdAttributes
    End With
    '
    ' Creates field matches for relationship.
    '
    For i = LBound(zRelationInfo.rdFieldName) To UBound(zRelationInfo.rdFieldName)
        Set myField = myRelation.CreateField(zRelationInfo.rdFieldName(i))
        myField.ForeignName = zRelationInfo.rdForeignName(i)
        myRelation.Fields.Append myField
    Next i
    ' Save Relation definition by appending it to Relations collection.
    oDatabase.Relations.Append myRelation
    If Err <> 0 Then DisplayError "AddRelation().Append: " & zRelationInfo.rdName
errorhandler:
    InitRelation zRelationInfo
End Sub

'
' InitField() initializes the FieldDesign
' Type to 0-Number, False-Boolean, and ""-String
'
Private Sub InitField(zField As FieldDesign)
    With zField
        .fdName = ""
        .fdType = 0
        .fdSize = 0
        .fdAllowZeroLength = False
        .fdAttributes = 0
        .fdDefaultValue = ""
        .fdOrdinalPosition = 0
        .fdRequired = False
        .fdValidationRule = ""
        .fdValidationText = ""
    End With
End Sub

'
' InitIndex() initializes the IndexDesign
' Type to 0-Number, False-Boolean, and ""-String
'
Private Sub InitIndex(zIndex As IndexDesign)
    Dim i As Integer

    With zIndex
        .idClustered = False
        .idIgnoreNulls = False
        .idName = ""
        .idPrimary = False
        .idRequired = False
        .idUnique = False
    End With
    If zIndex.idInitialized Then
        For i = LBound(zIndex.idFieldName) To UBound(zIndex.idFieldName)
            zIndex.idFieldName(i) = ""
        Next i
    End If
End Sub

'
' InitRelation() initializes the RelationDesign
' Type to 0-Number, False-Boolean, and ""-String
'
Private Sub InitRelation(zRelation As RelationDesign)
    Dim i As Integer

    With zRelation
        .rdAttributes = 0
        .rdName = ""
        .rdTable = ""
        .rdForeignTable = ""
    End With
    If zRelation.rdInitialized Then
        For i = LBound(zRelation.rdFieldName) To UBound(zRelation.rdFieldName)
            zRelation.rdFieldName(i) = ""
            zRelation.rdForeignName(i) = ""
        Next i
    End If
End Sub


' CreateLibraryDB() is the main routine which creates the
' database.  This function is unique for this particular database.
'
Public Sub CreateLibDB(FileName As String)
    Dim myTable As TableDef
    Dim zField As FieldDesign
    Dim zIndex As IndexDesign
    Dim zRelation As RelationDesign
    Dim myQuery As QueryDef

    On Error Resume Next
'    CreateLibraryDB = True
    zIndex.idInitialized = False
    zRelation.rdInitialized = False
    InitField zField
    InitIndex zIndex
    InitRelation zRelation
    Set LibraryDB = CreateDatabase(FileName, dbLangGeneral)
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateDatabase"
        Exit Sub
    End If
    
    
    ' Create the Tables
    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("LANGUAGE")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: LANGUAGE"
        Exit Sub
    End If
    With zField
        .fdName = "LANGUAGE_CODE"
        .fdType = 10
        .fdSize = 3
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "LANGUAGE_DESC"
        .fdType = 10
        .fdSize = 20
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): LANGUAGE"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: LANGUAGE"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    zIndex.idInitialized = True
    With zIndex
        .idName = "LANGUAGE_CODE"
        .idFieldName(1) = "LANGUAGE_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "LANGUAGE_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: LANGUAGE"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("LOAN")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: LOAN"
        Exit Sub
    End If
    With zField
        .fdName = "PATRON_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ACQUISITION_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
'        .fdDefaultValue = "0"
        .fdOrdinalPosition = 2
'        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "DATE_BORROW"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    With zField
        .fdName = "DATE_RETURN"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 4
    End With
    CreateField myTable, zField

    With zField
        .fdName = "TOT_FINE"
        .fdType = 5
        .fdSize = 8
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 5
    End With
    CreateField myTable, zField

    With zField
        .fdName = "CLEARED_FINE"
        .fdType = 1
        .fdSize = 1
        .fdAttributes = 1
        .fdDefaultValue = "No"
        .fdOrdinalPosition = 6
    End With
    CreateField myTable, zField
    
    With zField
        .fdName = "DATE_CLEARED_FINE"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 7
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): LOAN"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: LOAN"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "ACQUISITION_NUM"
        .idFieldName(1) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PATRON_NUM"
        .idFieldName(1) = "PATRON_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 3)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "PATRON_NUM"
        .idFieldName(2) = "ACQUISITION_NUM"
        .idFieldName(3) = "DATE_BORROW"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: LOAN"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("MATERIAL")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: MATERIAL"
        Exit Sub
    End If
    With zField
        .fdName = "ACQUISITION_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
'        .fdDefaultValue = "0"
        .fdOrdinalPosition = 1
'        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "MATERIAL_CODE"
        .fdType = 10
        .fdSize = 2
        .fdAttributes = 2
        .fdOrdinalPosition = 2
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "LANGUAGE_CODE"
        .fdType = 10
        .fdSize = 3
        .fdAttributes = 2
        .fdOrdinalPosition = 3
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "SHELF_CODE"
        .fdType = 10
        .fdSize = 3
        .fdAttributes = 2
        .fdOrdinalPosition = 4
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "VENDOR_CODE"
        .fdType = 10
        .fdSize = 5
        .fdAttributes = 2
        .fdOrdinalPosition = 5
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "PUBLISHER_CODE"
        .fdType = 10
        .fdSize = 5
        .fdAllowZeroLength = True
        .fdAttributes = 2
        .fdOrdinalPosition = 6
    End With
    CreateField myTable, zField

    With zField
        .fdName = "CLASSIFICATION_NUM"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 7
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "AUTHOR1"
        .fdType = 10
        .fdSize = 30
        .fdAllowZeroLength = True
        .fdAttributes = 2
        .fdOrdinalPosition = 8
    End With
    CreateField myTable, zField

    With zField
        .fdName = "AUTHOR2"
        .fdType = 10
        .fdSize = 30
        .fdAllowZeroLength = True
        .fdAttributes = 2
        .fdOrdinalPosition = 9
    End With
    CreateField myTable, zField

    With zField
        .fdName = "AUTHOR3"
        .fdType = 10
        .fdSize = 30
        .fdAllowZeroLength = True
        .fdAttributes = 2
        .fdOrdinalPosition = 10
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ISBN_NUM"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 11
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "EDITION"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 12
    End With
    CreateField myTable, zField

    With zField
        .fdName = "SINOPSIS"
        .fdType = 10
        .fdSize = 50
        .fdAllowZeroLength = True
        .fdAttributes = 2
        .fdOrdinalPosition = 13
    End With
    CreateField myTable, zField

    With zField
        .fdName = "YEAR_PUBLISHED"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 14
        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "PLACE_PUBLISHED"
        .fdType = 10
        .fdSize = 50
        .fdAllowZeroLength = True
        .fdAttributes = 2
        .fdOrdinalPosition = 15
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ON-LOAN"
        .fdType = 1
        .fdSize = 1
        .fdAttributes = 1
        .fdOrdinalPosition = 16
    End With
    CreateField myTable, zField

    With zField
        .fdName = "RESERVE-LIST"
        .fdType = 1
        .fdSize = 1
        .fdAttributes = 1
        .fdOrdinalPosition = 17
    End With
    CreateField myTable, zField

    With zField
        .fdName = "EXISTENCE"
        .fdType = 1
        .fdSize = 1
        .fdAttributes = 1
        .fdOrdinalPosition = 18
    End With
    CreateField myTable, zField

    With zField
        .fdName = "REFERENCE_ONLY"
        .fdType = 1
        .fdSize = 1
        .fdAttributes = 1
        .fdOrdinalPosition = 19
    End With
    CreateField myTable, zField

    With zField
        .fdName = "TITLE"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 20
        .fdRequired = True
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): MATERIAL"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: MATERIAL"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "ACQUISITION_NUM"
        .idFieldName(1) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "CLASSIFICATION_NUM"
        .idFieldName(1) = "CLASSIFICATION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "ISBN_NUM"
        .idFieldName(1) = "ISBN_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "LANGUAGE_CODE"
        .idFieldName(1) = "LANGUAGE_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "MATERIAL_CODE"
        .idFieldName(1) = "MATERIAL_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PUBLISHER_CODE"
        .idFieldName(1) = "PUBLISHER_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "SHELF_CODE"
        .idFieldName(1) = "SHELF_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "VENDOR_CODE"
        .idFieldName(1) = "VENDOR_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: MATERIAL"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("MATERIAL-TYPE")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: MATERIAL-TYPE"
        Exit Sub
    End If
    With zField
        .fdName = "MATERIAL_CODE"
        .fdType = 10
        .fdSize = 2
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "MATERIAL_DESC"
        .fdType = 10
        .fdSize = 30
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    With zField
        .fdName = "DURATION_OF_BORROW"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): MATERIAL-TYPE"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: MATERIAL-TYPE"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "MATERIAL_CODE"
        .idFieldName(1) = "MATERIAL_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "MATERIAL_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: MATERIAL-TYPE"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("MEMBER-TYPE")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: MEMBER-TYPE"
        Exit Sub
    End If
    With zField
        .fdName = "MEMBER_CODE"
        .fdType = 10
        .fdSize = 3
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "MEMBER_DESC"
        .fdType = 10
        .fdSize = 20
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    With zField
        .fdName = "MAX_BORROWING"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    With zField
        .fdName = "BORROWING_DURATION"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 5
    End With
    CreateField myTable, zField

    With zField
        .fdName = "FINE_RATE_PERDAY"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 6
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): MEMBER-TYPE"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: MEMBER-TYPE"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "MEMBER_CODE"
        .idFieldName(1) = "MEMBER_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "MEMBER_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: MEMBER-TYPE"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("PATRON")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: PATRON"
        Exit Sub
    End If
    With zField
        .fdName = "PATRON_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "MEMBER_CODE"
        .fdType = 10
        .fdSize = 3
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    With zField
        .fdName = "IC_NUM"
        .fdType = 10
        .fdSize = 14
        .fdAttributes = 2
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    With zField
        .fdName = "NAME"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 4
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ADDRESS"
        .fdType = 10
        .fdSize = 100
        .fdAttributes = 2
        .fdOrdinalPosition = 5
    End With
    CreateField myTable, zField

    With zField
        .fdName = "TELEPHONE_NUM"
        .fdType = 10
        .fdSize = 14
        .fdAttributes = 2
        .fdOrdinalPosition = 6
    End With
    CreateField myTable, zField

    With zField
        .fdName = "TOT_ITEM_BORROWED"
        .fdType = 6
        .fdSize = 4
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 7
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ACTIVE_STATUS"
        .fdType = 1
        .fdSize = 1
        .fdAttributes = 1
        .fdOrdinalPosition = 8
    End With
    CreateField myTable, zField

    With zField
        .fdName = "COURSE_DEPT"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 9
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): PATRON"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: PATRON"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "IC_NUM"
        .idFieldName(1) = "IC_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "MEMBER_CODE"
        .idFieldName(1) = "MEMBER_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PATRON_NUM"
        .idUnique = True
        .idFieldName(1) = "PATRON_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "PATRON_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "TELEPHONE_NUM"
        .idFieldName(1) = "TELEPHONE_NUM"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: PATRON"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("PLACEMENT")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: PLACEMENT"
        Exit Sub
    End If
    With zField
        .fdName = "SHELF_CODE"
        .fdType = 10
        .fdSize = 3
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "SHELF_DESC"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): PLACEMENT"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: PLACEMENT"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "SHELF_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "SHELF_CODE"
        .idFieldName(1) = "SHELF_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: PLACEMENT"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("PUBLISHER")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: PUBLISHER"
        Exit Sub
    End If
    With zField
        .fdName = "PUBLISHER_CODE"
        .fdType = 10
        .fdSize = 5
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "PUBLISHER_NAME"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): PUBLISHER"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: PUBLISHER"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "PUBLISHER_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PUBLISHER_CODE"
        .idFieldName(1) = "PUBLISHER_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: PUBLISHER"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("RESERVE")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: RESERVE"
        Exit Sub
    End If
    With zField
        .fdName = "ACQUISITION_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
'        .fdDefaultValue = "0"
        .fdOrdinalPosition = 1
'        .fdRequired = True
    End With
    CreateField myTable, zField

    With zField
        .fdName = "PATRON_NUM"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    With zField
        .fdName = "BOOKING_DATE"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    With zField
        .fdName = "RECEIVE_DATE"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 4
    End With
    CreateField myTable, zField

    With zField
        .fdName = "EXPIRY_BOOKING_DATE"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 5
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): RESERVE"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: RESERVE"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "ACQUISITION_NUM"
        .idFieldName(1) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PATRON_NUM"
        .idFieldName(1) = "PATRON_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 3)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "ACQUISITION_NUM"
        .idFieldName(2) = "PATRON_NUM"
        .idFieldName(3) = "BOOKING_DATE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: RESERVE"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("SUBJECT")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: SUBJECT"
        Exit Sub
    End If
    With zField
        .fdName = "SUBJECT_CODE"
        .fdType = 10
        .fdSize = 2
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "SUBJECT_DESC"
        .fdType = 10
        .fdSize = 20
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): SUBJECT"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: SUBJECT"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "SUBJECT_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "SUBJECT_CODE"
        .idFieldName(1) = "SUBJECT_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: SUBJECT"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("SUBJECT-MATERIAL")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: SUBJECT-MATERIAL"
        Exit Sub
    End If
    With zField
        .fdName = "SUBJECT_CODE"
        .fdType = 10
        .fdSize = 2
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ACQUISITION_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
'        .fdDefaultValue = "0"
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): SUBJECT-MATERIAL"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: SUBJECT-MATERIAL"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "ACQUISITION_NUM"
        .idFieldName(1) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 2)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "SUBJECT_CODE"
        .idFieldName(2) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "SUBJECT_CODE"
        .idFieldName(1) = "SUBJECT_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: SUBJECT-MATERIAL"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("SUPPLY")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: SUPPLY"
        Exit Sub
    End If
    With zField
        .fdName = "ACQUISITION_NUM"
        .fdType = 10
        .fdSize = 15
        .fdAttributes = 2
'        .fdDefaultValue = "0"
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "VENDOR_CODE"
        .fdType = 10
        .fdSize = 5
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    With zField
        .fdName = "DATE_OF_SUPPLY"
        .fdType = 8
        .fdSize = 8
        .fdAttributes = 1
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    With zField
        .fdName = "COST"
        .fdType = 5
        .fdSize = 8
        .fdAttributes = 1
        .fdDefaultValue = "0"
        .fdOrdinalPosition = 4
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): SUPPLY"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: SUPPLY"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "ACQUISITION_NUM"
        .idFieldName(1) = "ACQUISITION_NUM"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 2)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "ACQUISITION_NUM"
        .idFieldName(2) = "VENDOR_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "VENDOR_CODE"
        .idFieldName(1) = "VENDOR_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: SUPPLY"
        Exit Sub
    End If

    ' Table, Field, and Index Creation
    Set myTable = LibraryDB.CreateTableDef("VENDOR")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateTable: VENDOR"
        Exit Sub
    End If
    With zField
        .fdName = "VENDOR_CODE"
        .fdType = 10
        .fdSize = 5
        .fdAttributes = 2
        .fdOrdinalPosition = 1
    End With
    CreateField myTable, zField

    With zField
        .fdName = "VENDOR_NAME"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 2
    End With
    CreateField myTable, zField

    With zField
        .fdName = "ADDRESS"
        .fdType = 10
        .fdSize = 100
        .fdAttributes = 2
        .fdOrdinalPosition = 3
    End With
    CreateField myTable, zField

    With zField
        .fdName = "FAX_NUMBER"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 4
    End With
    CreateField myTable, zField

    With zField
        .fdName = "TELEPHONE_OFF"
        .fdType = 10
        .fdSize = 11
        .fdAttributes = 2
        .fdOrdinalPosition = 5
    End With
    CreateField myTable, zField

    With zField
        .fdName = "TELEPHONE_HP"
        .fdType = 10
        .fdSize = 11
        .fdAttributes = 2
        .fdOrdinalPosition = 6
    End With
    CreateField myTable, zField

    With zField
        .fdName = "CONTACT_PERSON"
        .fdType = 10
        .fdSize = 50
        .fdAttributes = 2
        .fdOrdinalPosition = 7
    End With
    CreateField myTable, zField

    If Err <> 0 Then
        DisplayError "CreateLibraryDB(): VENDOR"
        Exit Sub
    End If
    LibraryDB.TableDefs.Append myTable
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AppendTable: VENDOR"
        Exit Sub
    End If
    ' Indexes for the current table
    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "PrimaryKey"
        .idPrimary = True
        .idRequired = True
        .idUnique = True
        .idFieldName(1) = "VENDOR_CODE"
    End With
    AddIndex myTable, zIndex

    ReDim zIndex.idFieldName(1 To 1)
    With zIndex
        .idName = "VENDOR_CODE"
        .idFieldName(1) = "VENDOR_CODE"
    End With
    AddIndex myTable, zIndex

    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddIndex: VENDOR"
        Exit Sub
    End If

    ' Query Definition Creation
    Set myQuery = LibraryDB.CreateQueryDef("Analysis of books stored in the library based on subjects", "SELECT [SUBJECT-MATERIAL].SUBJECT_CODE, SUBJECT.SUBJECT_DESC, [SUBJECT-MATERIAL].ACQUISITION_NUM, MATERIAL.TITLE FROM SUBJECT INNER JOIN (MATERIAL INNER JOIN [SUBJECT-MATERIAL] ON MATERIAL.ACQUISITION_NUM = [SUBJECT-MATERIAL].ACQUISITION_NUM) ON SUBJECT.SUBJECT_CODE = [SUBJECT-MATERIAL].SUBJECT_CODE;")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateQueryDef: Analysis of books stored in the library based on subjects"
        Exit Sub
    End If
    myQuery.Close
    ' Query Definition Creation
    Set myQuery = LibraryDB.CreateQueryDef("Booking", "SELECT RESERVE.PATRON_NUM, PATRON.NAME, RESERVE.ACQUISITION_NUM, MATERIAL.TITLE, RESERVE.RECEIVE_DATE, RESERVE.EXPIRY_BOOKING_DATE FROM PATRON INNER JOIN (MATERIAL INNER JOIN RESERVE ON MATERIAL.ACQUISITION_NUM = RESERVE.ACQUISITION_NUM) ON PATRON.PATRON_NUM = RESERVE.PATRON_NUM;")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateQueryDef: Booking"
        Exit Sub
    End If
    myQuery.Close
    ' Query Definition Creation
    Set myQuery = LibraryDB.CreateQueryDef("Material Used by certain Patron", "SELECT LOAN.PATRON_NUM, LOAN.ACQUISITION_NUM, MATERIAL.TITLE, PATRON.NAME, PATRON.COURSE_DEPT FROM PATRON INNER JOIN (MATERIAL INNER JOIN LOAN ON MATERIAL.ACQUISITION_NUM = LOAN.ACQUISITION_NUM) ON PATRON.PATRON_NUM = LOAN.PATRON_NUM;")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateQueryDef: Material Used by certain Patron"
        Exit Sub
    End If
    myQuery.Close
    ' Query Definition Creation
    Set myQuery = LibraryDB.CreateQueryDef("Reserve Detail", "SELECT RESERVE.PATRON_NUM, PATRON.NAME, RESERVE.ACQUISITION_NUM, MATERIAL.TITLE, RESERVE.RECEIVE_DATE, RESERVE.EXPIRY_BOOKING_DATE FROM PATRON INNER JOIN (MATERIAL INNER JOIN RESERVE ON MATERIAL.ACQUISITION_NUM = RESERVE.ACQUISITION_NUM) ON PATRON.PATRON_NUM = RESERVE.PATRON_NUM;")
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().CreateQueryDef: Reserve Detail"
        Exit Sub
    End If
    myQuery.Close
'    ' Query Definition Creation
'    Set myQuery = LibraryDB.CreateQueryDef("Materials used based on material type (borrowed)", "SELECT  FROM MATERIAL INNER JOIN LOAN ON MATERIAL.ACQUISITION_NUM = LOAN.ACQUISITION_NUM;")
'    If Err <> 0 Then
'        DisplayError "CreateLibraryDB().CreateQueryDef: Materials used based on material type (borrowed)"
'        exit sub
'    End If
'    myQuery.Close
    ' Query Definition Creation
'    Set myQuery = LibraryDB.CreateQueryDef("Query1", "SELECT LOAN.PATRON_NUM, PATRON.TOT_ITEM_BORROWED FROM PATRON INNER JOIN LOAN ON PATRON.PATRON_NUM = LOAN.PATRON_NUM WHERE TOT_ITEM_BORROWED >0;")
'    If Err <> 0 Then
'        DisplayError "CreateLibraryDB().CreateQueryDef: Query1"
'        Exit Sub
'    End If
'    myQuery.Close
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    zRelation.rdInitialized = True
    With zRelation
        .rdName = "LANGUAGEMATERIAL"
        .rdTable = "LANGUAGE"
        .rdForeignTable = "MATERIAL"
        .rdFieldName(1) = "LANGUAGE_CODE"
        .rdForeignName(1) = "LANGUAGE_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: LANGUAGEMATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "MATERIAL-TYPEMATERIAL"
        .rdTable = "MATERIAL-TYPE"
        .rdForeignTable = "MATERIAL"
        .rdFieldName(1) = "MATERIAL_CODE"
        .rdForeignName(1) = "MATERIAL_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: MATERIAL-TYPEMATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "MATERIALLOAN"
        .rdTable = "MATERIAL"
        .rdForeignTable = "LOAN"
        .rdFieldName(1) = "ACQUISITION_NUM"
        .rdForeignName(1) = "ACQUISITION_NUM"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: MATERIALLOAN"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "MATERIALRESERVE"
        .rdTable = "MATERIAL"
        .rdForeignTable = "RESERVE"
        .rdFieldName(1) = "ACQUISITION_NUM"
        .rdForeignName(1) = "ACQUISITION_NUM"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: MATERIALRESERVE"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "MATERIALSUBJECT-MATERIAL"
        .rdTable = "MATERIAL"
        .rdForeignTable = "SUBJECT-MATERIAL"
        .rdFieldName(1) = "ACQUISITION_NUM"
        .rdForeignName(1) = "ACQUISITION_NUM"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: MATERIALSUBJECT-MATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "MATERIALSUPPLY"
        .rdTable = "MATERIAL"
        .rdForeignTable = "SUPPLY"
        .rdFieldName(1) = "ACQUISITION_NUM"
        .rdForeignName(1) = "ACQUISITION_NUM"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: MATERIALSUPPLY"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "MEMBER-TYPEPATRON"
        .rdTable = "MEMBER-TYPE"
        .rdForeignTable = "PATRON"
        .rdFieldName(1) = "MEMBER_CODE"
        .rdForeignName(1) = "MEMBER_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: MEMBER-TYPEPATRON"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "PATRONLOAN"
        .rdTable = "PATRON"
        .rdForeignTable = "LOAN"
        .rdFieldName(1) = "PATRON_NUM"
        .rdForeignName(1) = "PATRON_NUM"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: PATRONLOAN"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "PATRONRESERVE"
        .rdTable = "PATRON"
        .rdForeignTable = "RESERVE"
        .rdFieldName(1) = "PATRON_NUM"
        .rdForeignName(1) = "PATRON_NUM"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: PATRONRESERVE"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "PLACEMENTMATERIAL"
        .rdTable = "PLACEMENT"
        .rdForeignTable = "MATERIAL"
        .rdFieldName(1) = "SHELF_CODE"
        .rdForeignName(1) = "SHELF_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: PLACEMENTMATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "PUBLISHERMATERIAL"
        .rdTable = "PUBLISHER"
        .rdForeignTable = "MATERIAL"
        .rdFieldName(1) = "PUBLISHER_CODE"
        .rdForeignName(1) = "PUBLISHER_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: PUBLISHERMATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "SUBJECTSUBJECT-MATERIAL"
        .rdTable = "SUBJECT"
        .rdForeignTable = "SUBJECT-MATERIAL"
        .rdFieldName(1) = "SUBJECT_CODE"
        .rdForeignName(1) = "SUBJECT_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: SUBJECTSUBJECT-MATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "VENDORMATERIAL"
        .rdTable = "VENDOR"
        .rdForeignTable = "MATERIAL"
        .rdFieldName(1) = "VENDOR_CODE"
        .rdForeignName(1) = "VENDOR_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: VENDORMATERIAL"
        Exit Sub
    End If
    ' Relationship Creation
    ReDim zRelation.rdFieldName(1 To 1)
    ReDim zRelation.rdForeignName(1 To 1)
    With zRelation
        .rdName = "VENDORSUPPLY"
        .rdTable = "VENDOR"
        .rdForeignTable = "SUPPLY"
        .rdFieldName(1) = "VENDOR_CODE"
        .rdForeignName(1) = "VENDOR_CODE"
    End With
    AddRelation LibraryDB, zRelation
    If Err <> 0 Then
        DisplayError "CreateLibraryDB().AddRelation: VENDORSUPPLY"
        Exit Sub
    End If
    LibraryDB.Close
End Sub

